[package]
name = "img_info"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.1"
dirs = "6.0.0"
rexif = "0.7.5"
regex = "1.11.1"
image = "0.25.6"
console = "0.16.0"
walkdir = "2.5.0"
indicatif = "0.18.0"
lazy_static = "1.5.0"